// SPDX-License-Identifier: MIT
// Generate a self-signed RS256 keypair + JWKS for the OFFLINE MOCK ISSUER.
// TEST/DEMO ONLY — this key never signs anything real and is not a World key.
// Writes:
//   test/fixtures/mock-jwks.json        (public JWKS the Worker verifies against)
//   test/fixtures/mock-private.jwk.json (private JWK the mint script signs with)
//   .dev.vars                           (wrangler dev local secrets, git-ignored)
import { generateKeyPair, exportJWK } from "jose";
import { writeFileSync, mkdirSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const fixtures = join(root, "test", "fixtures");
mkdirSync(fixtures, { recursive: true });

const KID = "mock-issuer-key-1";
const ISSUER = "https://mock.trinity.local";
const CLIENT_ID = "trinity-demo-client";
const ADMIN_KEY = "dev-admin-key-change-me";

const { publicKey, privateKey } = await generateKeyPair("RS256", { extractable: true });
const pub = await exportJWK(publicKey);
const priv = await exportJWK(privateKey);
pub.kid = KID; pub.alg = "RS256"; pub.use = "sig";
priv.kid = KID; priv.alg = "RS256";

const jwks = { keys: [pub] };
writeFileSync(join(fixtures, "mock-jwks.json"), JSON.stringify(jwks, null, 2));
writeFileSync(join(fixtures, "mock-private.jwk.json"), JSON.stringify(priv, null, 2));

const devVars = [
  `# Generated by scripts/mkkeys.mjs — OFFLINE MOCK ISSUER (test/demo only). git-ignored.`,
  `ISSUER_OVERRIDE = "${ISSUER}"`,
  `WID_CLIENT_ID = "${CLIENT_ID}"`,
  `ADMIN_KEY = "${ADMIN_KEY}"`,
  `MOCK_JWKS = '${JSON.stringify(jwks)}'`,
  ``,
].join("\n");
writeFileSync(join(root, ".dev.vars"), devVars);

console.log("wrote test/fixtures/mock-jwks.json, test/fixtures/mock-private.jwk.json, .dev.vars");
console.log(JSON.stringify({ issuer: ISSUER, client_id: CLIENT_ID, kid: KID }, null, 2));
