// report.mjs — severity model + report rendering for spector-scan
// Spector 🕵️ — reviews, not audits.

export const SEV = {
  BLOCKER: { rank: 3, emoji: "🔴", label: "BLOCKER" },
  SHOULD:  { rank: 2, emoji: "🟡", label: "SHOULD" },
  NICE:    { rank: 1, emoji: "🟢", label: "NICE" },
  INFO:    { rank: 0, emoji: "ℹ️", label: "INFO" },
};

// A finding is:
// { id, sev, title, endpoint, evidence, cf_gate, f_id, recommendation }

export function summarize(findings) {
  const counts = { BLOCKER: 0, SHOULD: 0, NICE: 0, INFO: 0 };
  for (const f of findings) counts[f.sev.label]++;
  return counts;
}

// Clean = no BLOCKER and no SHOULD findings. INFO/NICE are advisory.
export function isClean(findings) {
  return findings.every((f) => f.sev.rank < 2);
}

export function verdict(findings) {
  const c = summarize(findings);
  if (c.BLOCKER > 0) return "FAIL — blocking weaknesses present";
  if (c.SHOULD > 0) return "WARN — non-blocking weaknesses present";
  return "PASS — no blocking or should-fix weaknesses found";
}

export function renderMarkdown({ target, startedAt, durationMs, findings, checksRun, notes, mode, filesScanned }) {
  const c = summarize(findings);
  const v = verdict(findings);
  const isStatic = mode === "static";
  const lines = [];
  lines.push(`# 🕵️ spector-scan — Consent-Backend Security Scan Report${mode ? ` (${isStatic ? "STATIC source" : "DYNAMIC black-box"})` : ""}`);
  lines.push("");
  lines.push(`**${isStatic ? "Source" : "Target"}**: \`${target}\``);
  lines.push(`**Scanned**: ${startedAt} (${durationMs} ms)`);
  lines.push(`**Checks run**: ${checksRun}${isStatic && typeof filesScanned === "number" ? ` · files scanned: ${filesScanned}` : ""}`);
  lines.push(`**Verdict**: ${v}`);
  lines.push(
    `**Findings**: ${c.BLOCKER} 🔴 BLOCKER · ${c.SHOULD} 🟡 SHOULD · ${c.NICE} 🟢 NICE · ${c.INFO} ℹ️ INFO`
  );
  lines.push("");
  if (isStatic) {
    lines.push(
      "> Scope: **static source + config analysis** of a backend source tree (no running " +
        "server). Flags F-class threats by reading files: F6 hosted-verify presence, F11 " +
        "endpoint auth (revoke capability / admin-key), 0.0.0.0 binds, secrets in committed " +
        "files, fail-open paths, jti/nonce replay guard, scope-escalation guard, JWT alg + " +
        "iss/aud pinning, CORS wildcard, .gitignore hygiene. Runtime-only properties (real " +
        "JWKS fetch, live jti burn) are re-checked dynamically with `--target`."
    );
  } else {
    lines.push(
      "> Scope: black-box, **unauthenticated** HTTP probe from the attacker's position " +
        "(venue Wi-Fi, no credentials). Some server-side properties (real-token JWKS verify, " +
        "jti-burn replay) can only be fully proven with a live World token — those are marked " +
        "`needs-live-token` and re-run at the Friday round-trip bell."
    );
  }
  lines.push("");

  if (findings.length === 0) {
    lines.push("_No findings. Target passed every probe in scope._");
  } else {
    // sort by severity desc, then id
    const sorted = [...findings].sort(
      (a, b) => b.sev.rank - a.sev.rank || a.id.localeCompare(b.id)
    );
    lines.push("## Findings");
    lines.push("");
    lines.push("| Sev | ID | Finding | Endpoint | Maps to |");
    lines.push("|---|---|---|---|---|");
    for (const f of sorted) {
      const maps = [f.cf_gate, f.f_id].filter(Boolean).join(" / ") || "—";
      lines.push(
        `| ${f.sev.emoji} ${f.sev.label} | ${f.id} | ${escPipe(f.title)} | \`${f.endpoint || "—"}\` | ${maps} |`
      );
    }
    lines.push("");
    lines.push("## Detail");
    lines.push("");
    for (const f of sorted) {
      lines.push(`### ${f.sev.emoji} ${f.id} — ${f.title}`);
      lines.push("");
      if (f.endpoint) lines.push(`- **Endpoint**: \`${f.endpoint}\``);
      if (f.cf_gate) lines.push(`- **CF gate**: ${f.cf_gate}`);
      if (f.f_id) lines.push(`- **Finding ref**: ${f.f_id}`);
      lines.push(`- **Evidence**: ${f.evidence}`);
      lines.push(`- **Fix**: ${f.recommendation}`);
      lines.push("");
    }
  }

  if (notes && notes.length) {
    lines.push("## Probe log (what was tried)");
    lines.push("");
    for (const n of notes) lines.push(`- ${n}`);
    lines.push("");
  }

  lines.push("---");
  lines.push("_Generated by spector-scan · Spector 🕵️ · reviews, not certified audits._");
  return lines.join("\n");
}

function escPipe(s) {
  return String(s).replace(/\|/g, "\\|");
}
